# Site settings
title: "Monica & Giacomo"
h2: "<div>Monica</div>üíç<div>Giacomo</div>"
description: |
    Villa Chiarelli, Renazzo di Cento

    9 Giugno 2019
owner: Giacomo Spettoli
first_published: 2019
baseurl: ""
url: "https://giacomos.github.io/wedding"

# Build settings
markdown: kramdown

wedding_gmap: https://goo.gl/maps/LuyktMwWLSr
wedding_date: 9 Giugno 2019
